{
  "bucketName": "umarvedantbucket",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "binary/octet-stream",
  "key": "accounts.data",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "versionId": null,
  "sseAwsKmsKeyId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "etag": "6bb452b033fc909967d3f5c79759acf3",
  "contentLength": 226,
  "lastModified": |2021-10-26T23:24:41|,
  "userMetadata": {},
  "redirectLocation": null
}