{
  "bucketName": "umarvedantbucket",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/csv",
  "key": "inventory.csv",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "sseAwsKmsKeyId": null,
  "versionId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "contentLength": 753,
  "etag": "eab9082e9bd84c0ceff1ee92d06dafd5",
  "lastModified": |2021-11-04T18:35:23|,
  "userMetadata": {},
  "redirectLocation": null
}